baseURL = "https://sahkonkilpailuttaja.fi/"
languageCode = "fi"
title = "Sähkönkilpailuttaja"
theme = "ananke"
pluralizelisttitles = false
summaryLength = 15

logo = "logo.webp"

MetaDataFormat = "yaml"
DefaultContentLanguage = "fi"
SectionPagesMenu = "main"
Paginate = 5 # this is set low for demonstrating with dummy content. Set to a higher number
googleAnalytics = ""
enableRobotsTXT = true

[sitemap]
  changefreq = "monthly"
  priority = 0.5
  filename = "sitemap.xml"

[params]
  favicon = "logo.webp"
  description = "Kilpailuta ja löydä parhaat sähkötarjoukset sivuiltamme!"
  facebook = "#"
  twitter = "#"
  instagram = "#"
  youtube = ""
  github = ""
  gitlab = ""
  linkedin = ""
  mastodon = ""
  # choose a background color from any on this page: http://tachyons.io/docs/themes/skins/ and preface it with "bg-"
  background_color_class = "bg-navy"
  featured_image = "/voimajutut.webp"
  recent_posts_number = 5

  pageNotFoundTitle = "404 - Sivua ei löytynyt"

  [menu]
  [[menu.main]]
    name = "Koti"
    url = "/"
    weight = 1

  [taxonomies]
  tag = "tags"

[permalinks]
  artikkelit = "/:filename/"

